select plan(26);
select has_column('public','faults','causes_service_interruption','fault records interruption decision');
select has_column('public','faults','interruption_id','fault links interruption');
select has_column('public','service_interruptions','fault_id','interruption links fault');
select has_column('public','service_interruptions','reported_at','report time preserved');
select has_column('public','service_interruptions','started_at_source','start source preserved');
select has_column('public','service_interruptions','start_time_reason','manual start reason exists');
select has_column('public','service_interruptions','stop_reading_id','stop evidence linked');
select has_column('public','service_interruptions','restart_reading_id','restart evidence linked');
select has_column('public','service_interruptions','potentially_affected_production_m3','derived production impact exists');
select has_column('public','service_interruptions','coverage_equivalent_person_days','theoretical coverage exists');
select has_function('public','mizan_report_fault_with_impact','governed fault/impact RPC exists');
select has_function('public','mizan_capture_interruption_meter_reading','governed interruption evidence RPC exists');
select has_function('public','mizan_restore_service_interruption','governed restoration RPC exists');
select has_function('public','mizan_maintenance_report','arbitrary-period maintenance report exists');
select has_function('public','mizan_register_asset','governed asset registration exists');
select is(has_table_privilege('anon','public.faults','INSERT'),false,'anon cannot insert faults');
select is(has_table_privilege('authenticated','public.faults','INSERT'),false,'authenticated cannot directly insert faults');
select is(has_table_privilege('authenticated','public.service_interruptions','INSERT'),false,'authenticated cannot directly insert interruptions');
select is(has_table_privilege('authenticated','public.maintenance_work_orders','INSERT'),false,'authenticated cannot directly insert work orders');
select is(has_table_privilege('authenticated','public.assets','INSERT'),false,'authenticated cannot directly insert assets');
select is(has_function_privilege('authenticated','public.mizan_report_service_interruption(uuid,text,text,text,text,text,timestamptz,integer,numeric)','EXECUTE'),false,'legacy interruption report RPC is retired');
select is(has_function_privilege('authenticated','public.mizan_update_service_interruption_status(uuid,text,text)','EXECUTE'),false,'legacy interruption status RPC is retired');
select is(has_function_privilege('authenticated','public.mizan_report_fault(uuid,text,text,text,uuid,uuid,uuid)','EXECUTE'),false,'legacy fault RPC is retired');
select is(has_function_privilege('authenticated','public.mizan_update_fault_status(uuid,text,text)','EXECUTE'),false,'legacy fault status RPC is retired');
select is(has_function_privilege('authenticated','public.mizan_update_work_order_status(uuid,text,text)','EXECUTE'),false,'legacy work-order status RPC is retired');
select is(has_function_privilege('authenticated','public.mizan_monthly_maintenance_report(uuid,date)','EXECUTE'),false,'legacy monthly report RPC is retired');
select * from finish();
