import { useEffect, useMemo, useState } from 'react';
import { BarChart3, AlertTriangle } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useProject } from '@/context/ProjectContext';

export function LossAnalysisPage() {
  const { currentProject } = useProject();
  const [rows, setRows] = useState<any[]>([]);
  useEffect(() => { let alive = true; (async () => { if (!currentProject) { setRows([]); return; } const { data } = await supabase.from('kpi_snapshots').select('period,period_start,period_end,water_production_m3,water_consumption_m3,nrw_percentage,data_completeness').eq('project_id', currentProject.id).order('period_start', { ascending: false }).limit(12); if (alive) setRows(data || []); })(); return () => { alive = false; }; }, [currentProject]);
  const summary = useMemo(() => rows.reduce((a,r) => ({ production:a.production+Number(r.water_production_m3||0), consumption:a.consumption+Number(r.water_consumption_m3||0) }), {production:0,consumption:0}), [rows]);
  const gap = Math.max(0, summary.production-summary.consumption); const pct = summary.production ? gap/summary.production*100 : 0;
  return <div className="space-y-6" dir="rtl"><div><h1 className="text-2xl md:text-3xl font-bold flex items-center gap-2"><BarChart3 className="w-6 h-6"/>تحليل الفاقد المائي</h1><p className="text-sm text-neutral-500 mt-1">تحليل الإنتاج والاستهلاك من مؤشرات المشروع.</p></div><div className="grid md:grid-cols-3 gap-4"><Metric title="الإنتاج" value={summary.production.toLocaleString('ar-YE')} unit="م³"/><Metric title="الاستهلاك" value={summary.consumption.toLocaleString('ar-YE')} unit="م³"/><Metric title="الفجوة" value={gap.toLocaleString('ar-YE')} unit={pct.toFixed(1)+'%'} alert={pct>15}/></div><div className="rounded-xl border bg-white overflow-hidden"><div className="p-4 border-b font-semibold">السجل الشهري</div>{rows.length===0?<div className="p-8 text-center text-neutral-500">لا توجد بيانات KPI لهذا المشروع.</div>:<table className="w-full text-sm"><thead className="bg-neutral-50"><tr><th className="p-3 text-right">الفترة</th><th className="p-3 text-right">الإنتاج</th><th className="p-3 text-right">الاستهلاك</th><th className="p-3 text-right">NRW</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t"><td className="p-3">{r.period}</td><td className="p-3">{Number(r.water_production_m3||0).toLocaleString('ar-YE')}</td><td className="p-3">{Number(r.water_consumption_m3||0).toLocaleString('ar-YE')}</td><td className="p-3">{Number(r.nrw_percentage||0).toFixed(1)}%</td></tr>)}</tbody></table>}</div>{pct>15&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 flex gap-3"><AlertTriangle className="w-5 h-5"/><span>الفجوة تتجاوز 15% ضمن البيانات المتاحة؛ يلزم التحقق من الإنتاج والقراءات.</span></div>}</div>;
}
function Metric({title,value,unit,alert=false}:{title:string;value:string;unit:string;alert?:boolean}) { return <div className={'rounded-xl border bg-white p-5 '+(alert?'border-amber-300':'')}><div className="text-sm text-neutral-500">{title}</div><div className="text-2xl font-bold mt-2">{value} <span className="text-sm font-normal text-neutral-500">{unit}</span></div></div>; }