import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, BellRing, Boxes, Clock3, FileText, Loader2, Plus, ShieldAlert, Wrench } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useProject } from '@/context/ProjectContext';
import { useAuth } from '@/context/AuthContext';
import { Badge } from '@/components/ui/Badge';
import { StatCard } from '@/components/ui/StatCard';
import { Modal } from '@/components/ui/Modal';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState, LoadingSpinner } from '@/lib/hooks';
import { formatCurrency, formatDate, formatNumber, formatRelativeTime, severityLabels, faultStatusLabels, workOrderStatusLabels } from '@/lib/utils';
import type { Fault, WorkOrder, Asset, Well, Pump } from '@/types';

type Interruption={id:string;project_id:string;interruption_number:string;interruption_type:string;severity:string;status:string;description:string|null;started_at:string;restored_at:string|null;closed_at:string|null;affected_subscribers:number;estimated_water_loss_m3:number;cause_category:string|null;reported_by:string|null};
type Tab='overview'|'faults'|'interruptions'|'workorders'|'assets'; type Form=Record<string,string>;
const interruptionLabels:Record<string,string>={service_stop:'توقف خدمة',pressure_drop:'انخفاض ضغط',production_stop:'توقف إنتاج',planned_shutdown:'توقف مخطط',emergency_shutdown:'توقف طارئ'};
const interruptionStatus:Record<string,string>={open:'مفتوح',investigating:'قيد التحقيق',mitigating:'قيد المعالجة',restored:'تمت الاستعادة',closed:'مغلق'};
const faultTypes:Record<string,string>={pump_failure:'عطل مضخة',pipe_leak:'تسريب أنبوب',electrical:'عطل كهربائي',meter_issue:'مشكلة عداد',water_quality:'جودة المياه',other:'أخرى'};

function printMemo(w:WorkOrder & {faults?:Fault}) {
  const e=(v:unknown)=>String(v??'—').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
  const html='<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>مذكرة صيانة '+e(w.work_order_number)+'</title><style>body{font-family:Arial;padding:35px;line-height:1.8}h1{margin:0 0 4px}h2{border-bottom:1px solid #ddd;padding-bottom:5px}table{width:100%;border-collapse:collapse;margin:10px 0 24px}td{border:1px solid #ddd;padding:8px}td:first-child{font-weight:bold;background:#f6f6f6;width:28%}.sign{margin-top:70px;display:grid;grid-template-columns:1fr 1fr;gap:60px}</style></head><body><h1>مذكرة صيانة</h1><div>رقم الأمر: <b>'+e(w.work_order_number)+'</b></div><hr><h2>البيانات</h2><table><tr><td>العطل المرتبط</td><td>'+e(w.faults?.fault_number)+'</td></tr><tr><td>الأولوية</td><td>'+e(severityLabels[w.priority]||w.priority)+'</td></tr><tr><td>الحالة</td><td>'+e(w.status==='completed'?'تم الحل':workOrderStatusLabels[w.status]||w.status)+'</td></tr><tr><td>المنفذ</td><td>'+e(w.assigned_to||'لم يخصص بعد')+'</td></tr><tr><td>التاريخ المجدول</td><td>'+e(w.scheduled_date)+'</td></tr></table><h2>وصف العمل</h2><p>'+e(w.description)+'</p><h2>الإغلاق</h2><table><tr><td>تاريخ الإكمال</td><td>'+e(w.completed_date)+'</td></tr><tr><td>التكلفة</td><td>'+e(formatCurrency(w.cost))+'</td></tr><tr><td>قطع الغيار</td><td>'+e(w.parts_used)+'</td></tr><tr><td>ملاحظات</td><td>'+e(w.notes)+'</td></tr></table><div class="sign"><div>اسم المنفذ وتوقيعه: __________________</div><div>اعتماد مدير المشروع: __________________</div></div><script>window.onload=function(){window.print()}</script></body></html>';
  const win=window.open('','_blank','noopener,noreferrer,width=900,height=800'); if(win){win.document.write(html);win.document.close();}
}

export function MaintenancePage(){
 const {currentProject}=useProject(); const {profile}=useAuth();
 const [tab,setTab]=useState<Tab>('overview'),[faults,setFaults]=useState<Fault[]>([]),[workOrders,setWorkOrders]=useState<(WorkOrder&{faults?:Fault})[]>([]),[assets,setAssets]=useState<Asset[]>([]),[wells,setWells]=useState<Well[]>([]),[pumps,setPumps]=useState<Pump[]>([]),[interruptions,setInterruptions]=useState<Interruption[]>([]);
 const [show,setShow]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState<Form>({}),[error,setError]=useState<string|null>(null),[formError,setFormError]=useState<string|null>(null);
 const load=async()=>{if(!currentProject)return;setError(null);const p=currentProject.id;const [f,w,a,ws,ps,i]=await Promise.all([supabase.from('faults').select('*').eq('project_id',p).order('reported_at',{ascending:false}),supabase.from('maintenance_work_orders').select('*, faults(fault_number,severity,description)').eq('project_id',p).order('created_at',{ascending:false}),supabase.from('assets').select('*').eq('project_id',p).order('asset_code'),supabase.from('wells').select('*').eq('project_id',p).order('code'),supabase.from('pumps').select('*').eq('project_id',p).order('code'),supabase.from('service_interruptions').select('*').eq('project_id',p).order('started_at',{ascending:false})]);const bad=[f,w,a,ws,ps,i].find(x=>x.error);if(bad?.error){setError(bad.error.message);return;}setFaults((f.data||[]) as Fault[]);setWorkOrders((w.data||[]) as any);setAssets((a.data||[]) as Asset[]);setWells((ws.data||[]) as Well[]);setPumps((ps.data||[]) as Pump[]);setInterruptions((i.data||[]) as Interruption[]);};
 useEffect(()=>{load()},[currentProject?.id]);
 const openFaults=useMemo(()=>faults.filter(f=>!['resolved','closed'].includes(f.status)),[faults]); const openWOs=useMemo(()=>workOrders.filter(w=>['open','in_progress'].includes(w.status)),[workOrders]); const openStops=useMemo(()=>interruptions.filter(i=>!['restored','closed'].includes(i.status)),[interruptions]);
 const openForm=(t:Tab)=>{setTab(t);setForm({severity:'medium',priority:'medium',type:'corrective'});setFormError(null);setShow(true)};
 const save=async()=>{if(!currentProject||!profile)return;setSaving(true);setFormError(null);try{
  if(tab==='faults'){if(!form.fault_type||!form.description?.trim())throw new Error('نوع العطل والوصف مطلوبان');const r=await supabase.from('faults').insert({project_id:currentProject.id,fault_type:form.fault_type,severity:form.severity||'medium',status:'reported',description:form.description.trim(),reported_by:profile.full_name,reporter_type:'staff',asset_id:form.asset_id||null,well_id:form.well_id||null,pump_id:form.pump_id||null}).select().single();if(r.error)throw r.error;await load();
  }else if(tab==='interruptions'){if(!form.description?.trim())throw new Error('وصف التوقف مطلوب');const r=await supabase.from('service_interruptions').insert({project_id:currentProject.id,interruption_type:form.interruption_type||'service_stop',severity:form.severity||'medium',status:'open',description:form.description.trim(),cause_category:form.cause_category||null,started_at:form.started_at||new Date().toISOString(),affected_subscribers:Number(form.affected_subscribers||0),estimated_water_loss_m3:Number(form.water_loss||0),reported_by:profile.id}).select().single();if(r.error)throw r.error;await load();
  }else if(tab==='workorders'){if(!form.description?.trim())throw new Error('وصف أمر الصيانة مطلوب');const r=await supabase.rpc('mizan_create_work_order',{p_project_id:currentProject.id,p_description:form.description.trim(),p_type:form.type||'corrective',p_priority:form.priority||'medium',p_assigned_to:null,p_scheduled_date:form.scheduled_date||null,p_fault_id:form.fault_id||null,p_asset_id:form.asset_id||null,p_well_id:form.well_id||null,p_pump_id:form.pump_id||null});if(r.error)throw r.error;await load();
  }else if(tab==='assets'){if(!form.name_ar?.trim())throw new Error('اسم الأصل مطلوب');const r=await supabase.from('assets').insert({project_id:currentProject.id,name_ar:form.name_ar.trim(),category:form.category||null,type:form.type||null,manufacturer:form.manufacturer||null,model:form.model||null,serial_number:form.serial_number||null,status:form.asset_status||'operational',purchase_cost:form.purchase_cost?Number(form.purchase_cost):null,expected_lifespan_years:form.expected_lifespan_years?Number(form.expected_lifespan_years):null,purchase_date:form.purchase_date||null,installation_date:form.installation_date||null}).select().single();if(r.error)throw r.error;await load();}
  setShow(false);setForm({});
 }catch(err){setFormError(err instanceof Error?err.message:'تعذر حفظ السجل')}finally{setSaving(false)}};
 const assign=async(w:WorkOrder)=>{const name=window.prompt('أدخل اسم الشخص الذي سيجري الصيانة:',w.assigned_to||'');if(!name?.trim())return;const date=window.prompt('التاريخ المجدول YYYY-MM-DD (اختياري):',w.scheduled_date||'')||null;const r=await supabase.rpc('mizan_assign_work_order',{p_work_order_id:w.id,p_assigned_to:name.trim(),p_scheduled_date:date});if(r.error)setError(r.error.message);else await load()};
 const status=async(w:WorkOrder,s:string)=>{const r=await supabase.rpc('mizan_update_work_order_status',{p_work_order_id:w.id,p_status:s});if(r.error)setError(r.error.message);else await load()};
 const faultStatus=async(f:Fault,s:string)=>{const u:any={status:s};if(s==='verified')u.verified_at=new Date().toISOString();if(s==='resolved')u.resolved_at=new Date().toISOString();const r=await supabase.from('faults').update(u).eq('id',f.id);if(r.error)setError(r.error.message);else await load()};
 const stopStatus=async(i:Interruption,s:string)=>{const u:any={status:s};if(s==='restored')u.restored_at=new Date().toISOString();if(s==='closed')u.closed_at=new Date().toISOString();const r=await supabase.from('service_interruptions').update(u).eq('id',i.id);if(r.error)setError(r.error.message);else await load()};
 if(!currentProject)return <div className="text-center py-20 text-neutral-400">اختر مشروعاً للبدء</div>;
 const tabs:[Tab,string,any,number][]=[['overview','المتابعة',ShieldAlert,openFaults.length+openStops.length],['faults','الأعطال',AlertTriangle,faults.length],['interruptions','التوقفات',Clock3,interruptions.length],['workorders','أوامر الصيانة',Wrench,workOrders.length],['assets','الأصول',Boxes,assets.length]];
 return <div className="space-y-6 animate-fade-in"><div className="flex items-center justify-between flex-wrap gap-3"><div><h1 className="text-2xl font-bold">الصيانة والأعطال والتوقفات</h1><p className="text-sm text-neutral-500 mt-1">سجل واحد من البلاغ إلى أمر الصيانة ثم الإغلاق</p></div><button className="btn-primary" onClick={()=>openForm(tab==='overview'?'faults':tab)}><Plus size={18}/> تسجيل {tab==='interruptions'?'توقف':tab==='workorders'?'أمر صيانة':tab==='assets'?'أصل':'عطل'}</button></div>
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><StatCard title="بلاغات مفتوحة" value={formatNumber(openFaults.length)} icon={AlertTriangle} color={openFaults.length?'error':'success'}/><StatCard title="أوامر قيد المعالجة" value={formatNumber(openWOs.length)} icon={Wrench} color={openWOs.length?'warning':'success'}/><StatCard title="توقفات مفتوحة" value={formatNumber(openStops.length)} icon={BellRing} color={openStops.length?'warning':'success'}/><StatCard title="أعطال حرجة" value={formatNumber(openFaults.filter(f=>['high','critical'].includes(f.severity)).length)} icon={ShieldAlert} color="error"/></div>
 <div className="flex gap-1 bg-neutral-100 p-1 rounded-xl w-fit flex-wrap">{tabs.map(([id,label,Icon,count])=><button key={id} onClick={()=>setTab(id)} className={'flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm '+(tab===id?'bg-white text-primary-700 shadow-sm':'text-neutral-500')}><Icon size={16}/>{label}<span className="text-xs px-1.5 py-0.5 rounded-full bg-neutral-200">{count}</span></button>)}</div>
 {error&&<ErrorState message={error} onRetry={load}/>} 
 {tab==='overview'&&<div className="grid md:grid-cols-2 gap-4"><div className="card p-5"><h2 className="font-bold mb-3">يحتاج إجراء</h2>{openFaults.slice(0,6).map(f=><div key={f.id} className="py-3 border-b"><b>{f.fault_number}</b><p className="text-sm">{f.description}</p></div>)}{openFaults.length===0&&<p className="text-sm text-neutral-400">لا توجد أعطال مفتوحة.</p>}</div><div className="card p-5"><h2 className="font-bold mb-3">أوامر الصيانة المفتوحة</h2>{openWOs.slice(0,6).map(w=><div key={w.id} className="py-3 border-b flex justify-between"><div><b>{w.work_order_number}</b><p className="text-sm">{w.description}</p></div><Badge status={w.status} label={w.status==='completed'?'تم الحل':workOrderStatusLabels[w.status]||w.status}/></div>)}</div></div>}
 {tab==='faults'&&<div className="space-y-3">{faults.length===0?<div className="card"><EmptyState icon={AlertTriangle} title="لا توجد أعطال" description="عند تسجيل عطل ينشئ النظام أمر صيانة تلقائياً."/></div>:faults.map(f=><div className="card p-4" key={f.id}><div className="flex justify-between gap-3"><div><div className="flex gap-2 flex-wrap"><b>{f.fault_number}</b><Badge status={f.severity} label={severityLabels[f.severity]||f.severity}/><Badge status={f.status} label={faultStatusLabels[f.status]||f.status}/></div><p className="mt-2">{f.description||'—'}</p><p className="text-xs text-neutral-400 mt-2">{faultTypes[f.fault_type||'']||f.fault_type||'—'} · {f.reported_by||'—'} · {formatRelativeTime(f.reported_at)}</p></div>{!['resolved','closed'].includes(f.status)&&<select className="input-field w-auto" value={f.status} onChange={e=>faultStatus(f,e.target.value)}><option value="reported">تم الإبلاغ</option><option value="verified">تم التحقق</option><option value="assigned">تم التعيين</option><option value="in_progress">قيد المعالجة</option><option value="resolved">تم الحل</option><option value="closed">مغلق</option></select>}</div></div>)}</div>}
 {tab==='interruptions'&&<div className="space-y-3">{interruptions.length===0?<div className="card"><EmptyState icon={Clock3} title="لا توجد توقفات" description="سجل توقف الخدمة أو الإنتاج عند حدوثه."/></div>:interruptions.map(i=><div className="card p-4" key={i.id}><div className="flex justify-between gap-3"><div><div className="flex gap-2"><b>{i.interruption_number}</b><Badge status={i.severity} label={severityLabels[i.severity]||i.severity}/><Badge status={i.status} label={interruptionStatus[i.status]||i.status}/></div><p className="font-medium mt-2">{interruptionLabels[i.interruption_type]||i.interruption_type}</p><p>{i.description||'—'}</p><p className="text-xs text-neutral-400 mt-2">{formatDate(i.started_at)} · المتأثرون {formatNumber(i.affected_subscribers)} · الفاقد {formatNumber(i.estimated_water_loss_m3)} م³</p></div>{i.status!=='closed'&&<select className="input-field w-auto" value={i.status} onChange={e=>stopStatus(i,e.target.value)}><option value="open">مفتوح</option><option value="investigating">قيد التحقيق</option><option value="mitigating">قيد المعالجة</option><option value="restored">تمت الاستعادة</option><option value="closed">مغلق</option></select>}</div></div>)}</div>}
 {tab==='workorders'&&<div className="card overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-right text-xs text-neutral-400 border-b bg-neutral-50"><th className="p-3">رقم الأمر</th><th className="p-3">العطل</th><th className="p-3">الأولوية</th><th className="p-3">المنفذ</th><th className="p-3">الحالة</th><th className="p-3">إجراءات</th></tr></thead><tbody>{workOrders.map(w=><tr key={w.id} className="border-b"><td className="p-3 font-semibold">{w.work_order_number}</td><td className="p-3">{w.faults?.fault_number||'—'}</td><td className="p-3"><Badge status={w.priority} label={severityLabels[w.priority]||w.priority}/></td><td className="p-3">{w.assigned_to||<span className="text-warning-600">غير معين</span>}</td><td className="p-3"><Badge status={w.status} label={w.status==='completed'?'تم الحل':workOrderStatusLabels[w.status]||w.status}/></td><td className="p-3 flex gap-3"><button className="text-primary-600 text-xs" onClick={()=>assign(w)}>تخصيص المنفذ</button>{w.status!=='completed'&&w.status!=='cancelled'&&<button className="text-primary-600 text-xs" onClick={()=>status(w,w.status==='open'?'in_progress':'completed')}>{w.status==='open'?'بدء المعالجة':'تم الحل'}</button>}<button className="text-neutral-600 text-xs flex gap-1 items-center" onClick={()=>printMemo(w)}><FileText size={14}/> المذكرة</button></td></tr>)}</tbody></table></div>}
 {tab==='assets'&&(assets.length===0?<div className="card"><EmptyState icon={Boxes} title="لا توجد أصول" description="أضف الأصل التشغيلي عند الحاجة."/></div>:<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{assets.map(a=><div className="card p-4" key={a.id}><b>{a.name_ar}</b><p className="text-xs text-neutral-400">{a.asset_code}</p><p className="text-sm mt-2">{a.category||'—'} {a.manufacturer?(' · '+a.manufacturer):''} {a.model?(' · '+a.model):''}</p></div>)}</div>)}
 <Modal open={show} onClose={()=>setShow(false)} title={tab==='faults'?'تسجيل عطل':tab==='interruptions'?'تسجيل توقف':tab==='workorders'?'إنشاء أمر صيانة':'إضافة أصل'} size="lg">
 {tab==='faults'&&<div className="grid md:grid-cols-2 gap-4"><div><label className="label-field">نوع العطل *</label><select className="input-field" value={form.fault_type||''} onChange={e=>setForm({...form,fault_type:e.target.value})}><option value="">— اختر —</option>{Object.entries(faultTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div><label className="label-field">الخطورة</label><select className="input-field" value={form.severity||'medium'} onChange={e=>setForm({...form,severity:e.target.value})}><option value="low">منخفض</option><option value="medium">متوسط</option><option value="high">عالٍ</option><option value="critical">حرج</option></select></div><div><label className="label-field">الأصل</label><select className="input-field" value={form.asset_id||''} onChange={e=>setForm({...form,asset_id:e.target.value})}><option value="">—</option>{assets.map(a=><option key={a.id} value={a.id}>{a.asset_code} - {a.name_ar}</option>)}</select></div><div><label className="label-field">المضخة</label><select className="input-field" value={form.pump_id||''} onChange={e=>setForm({...form,pump_id:e.target.value})}><option value="">—</option>{pumps.map(p=><option key={p.id} value={p.id}>{p.code}</option>)}</select></div><div><label className="label-field">البئر</label><select className="input-field" value={form.well_id||''} onChange={e=>setForm({...form,well_id:e.target.value})}><option value="">—</option>{wells.map(w=><option key={w.id} value={w.id}>{w.code}</option>)}</select></div><div className="md:col-span-2"><label className="label-field">وصف العطل *</label><textarea className="input-field min-h-24" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></div></div>}
 {tab==='interruptions'&&<div className="grid md:grid-cols-2 gap-4"><div><label className="label-field">نوع التوقف</label><select className="input-field" value={form.interruption_type||'service_stop'} onChange={e=>setForm({...form,interruption_type:e.target.value})}>{Object.entries(interruptionLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div><label className="label-field">الخطورة</label><select className="input-field" value={form.severity||'medium'} onChange={e=>setForm({...form,severity:e.target.value})}><option value="low">منخفض</option><option value="medium">متوسط</option><option value="high">عالٍ</option><option value="critical">حرج</option></select></div><div><label className="label-field">وقت البداية</label><input type="datetime-local" className="input-field" value={form.started_at||''} onChange={e=>setForm({...form,started_at:e.target.value})}/></div><div><label className="label-field">المشتركون المتأثرون</label><input type="number" min="0" className="input-field" value={form.affected_subscribers||'0'} onChange={e=>setForm({...form,affected_subscribers:e.target.value})}/></div><div><label className="label-field">الفاقد التقديري م³</label><input type="number" min="0" className="input-field" value={form.water_loss||'0'} onChange={e=>setForm({...form,water_loss:e.target.value})}/></div><div><label className="label-field">تصنيف السبب</label><input className="input-field" value={form.cause_category||''} onChange={e=>setForm({...form,cause_category:e.target.value})}/></div><div className="md:col-span-2"><label className="label-field">الوصف *</label><textarea className="input-field min-h-24" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></div></div>}
 {tab==='workorders'&&<div className="grid md:grid-cols-2 gap-4"><div><label className="label-field">نوع الصيانة</label><select className="input-field" value={form.type||'corrective'} onChange={e=>setForm({...form,type:e.target.value})}><option value="corrective">تصحيحية</option><option value="preventive">وقائية</option><option value="emergency">طارئة</option></select></div><div><label className="label-field">الأولوية</label><select className="input-field" value={form.priority||'medium'} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">منخفضة</option><option value="medium">متوسطة</option><option value="high">عالية</option><option value="urgent">عاجلة</option></select></div><div><label className="label-field">العطل المرتبط</label><select className="input-field" value={form.fault_id||''} onChange={e=>setForm({...form,fault_id:e.target.value})}><option value="">—</option>{faults.filter(f=>!['closed','resolved'].includes(f.status)).map(f=><option key={f.id} value={f.id}>{f.fault_number}</option>)}</select></div><div><label className="label-field">التاريخ المجدول</label><input type="date" className="input-field" value={form.scheduled_date||''} onChange={e=>setForm({...form,scheduled_date:e.target.value})}/></div><div className="md:col-span-2"><label className="label-field">الوصف *</label><textarea className="input-field min-h-24" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></div></div>}
 {tab==='assets'&&<div className="grid md:grid-cols-2 gap-4"><div><label className="label-field">رمز الأصل</label><div className="input-field bg-neutral-50 text-neutral-400">يُولّد تلقائياً</div></div><div><label className="label-field">الاسم *</label><input className="input-field" value={form.name_ar||''} onChange={e=>setForm({...form,name_ar:e.target.value})}/></div><div><label className="label-field">التصنيف</label><input className="input-field" value={form.category||''} onChange={e=>setForm({...form,category:e.target.value})}/></div><div><label className="label-field">المصنع</label><input className="input-field" value={form.manufacturer||''} onChange={e=>setForm({...form,manufacturer:e.target.value})}/></div><div><label className="label-field">الموديل</label><input className="input-field" value={form.model||''} onChange={e=>setForm({...form,model:e.target.value})}/></div><div><label className="label-field">الرقم التسلسلي</label><input className="input-field" value={form.serial_number||''} onChange={e=>setForm({...form,serial_number:e.target.value})}/></div></div>}
 {formError&&<div className="mt-4 p-3 rounded-lg bg-error-50 text-error-700 text-sm">{formError}</div>}<div className="flex gap-3 mt-6"><button className="btn-secondary flex-1" onClick={()=>setShow(false)}>إلغاء</button><button className="btn-primary flex-1" disabled={saving} onClick={save}>{saving?<><Loader2 size={16} className="animate-spin"/> جاري الحفظ...</>:'حفظ'}</button></div></Modal>
 </div>;
}