import { createContext, useContext, useState, useEffect, useRef, type ReactNode } from 'react';
import type { Session, User } from '@supabase/supabase-js';
import { supabase } from '@/lib/supabase';
import type { Profile, UserRole } from '@/types';

interface AuthContextValue { session: Session|null; user: User|null; profile: Profile|null; loading: boolean; signIn:(email:string,password:string)=>Promise<{error:string|null}>; requestPasswordReset:(email:string)=>Promise<{error:string|null}>; updatePassword:(password:string)=>Promise<{error:string|null}>; signOut:()=>Promise<void>; refreshProfile:()=>Promise<void>; }
const AuthContext=createContext<AuthContextValue|undefined>(undefined);
export const roleLabels:Record<UserRole,string>={platform_admin:'مدير المنصة',central_governance:'حوكمة هيئة مياه الريف',project_manager:'مدير المشروع',tenant_manager:'دور انتقالي',operations_officer:'مسؤول العمليات',meter_reader:'قارئ العدادات',collection_officer:'المحصل',maintenance_officer:'مسؤول الصيانة',technician:'فني',data_exception_officer:'مسؤول استثناءات البيانات',viewer:'عرض فقط'};
const PROFILE_LOAD_TIMEOUT_MS=10000, SIGN_IN_TIMEOUT_MS=15000, PASSWORD_RESET_TIMEOUT_MS=15000;
async function withTimeout<T>(promise:PromiseLike<T>,timeoutMs:number):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([promise,new Promise<T>((_,reject)=>{timer=setTimeout(()=>reject(new Error('REQUEST_TIMEOUT')),timeoutMs)})])}finally{if(timer)clearTimeout(timer)}}
export function AuthProvider({children}:{children:ReactNode}){
 const [session,setSession]=useState<Session|null>(null),[user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true);
 const signingInRef=useRef(false),bootstrapReadyRef=useRef(false);
 const fetchProfile=async(uid:string,userOverride?:User)=>{const currentUser=userOverride??user;try{const profileResult=await withTimeout(supabase.from('profiles').select('*').eq('id',uid).maybeSingle(),PROFILE_LOAD_TIMEOUT_MS);let {data}=profileResult;const {error}=profileResult;if(error){console.error('Failed to load profile:',error.message);return null}if(!data&&currentUser?.user_metadata?.onboarding_token){const {error:claimError}=await withTimeout(supabase.rpc('mizan_claim_subtenant_user_slot',{p_onboarding_token:currentUser.user_metadata.onboarding_token}),PROFILE_LOAD_TIMEOUT_MS);if(!claimError){await withTimeout(supabase.auth.updateUser({data:{onboarding_token:null}}),PROFILE_LOAD_TIMEOUT_MS);data=(await withTimeout(supabase.from('profiles').select('*').eq('id',uid).maybeSingle(),PROFILE_LOAD_TIMEOUT_MS)).data}else console.error('Failed to claim onboarding slot:',claimError.message)}return data as Profile|null}catch(error){console.error('Profile load failed:',error);return null}};
 const refreshProfile=async()=>{if(user)setProfile(await fetchProfile(user.id))};
 useEffect(()=>{let mounted=true;const loadInitialSession=async()=>{try{const {data:{session}}=await withTimeout(supabase.auth.getSession(),SIGN_IN_TIMEOUT_MS);if(!mounted)return;setSession(session);setUser(session?.user??null);if(session?.user)setProfile(await fetchProfile(session.user.id,session.user))}catch(error){console.error('Initial auth session load failed:',error)}finally{if(mounted){bootstrapReadyRef.current=true;setLoading(false)}};void loadInitialSession();const {data:{subscription}}=supabase.auth.onAuthStateChange((event,s)=>{if(!mounted)return;setSession(s);setUser(s?.user??null);if(event==='SIGNED_OUT'&&bootstrapReadyRef.current)setProfile(null)});return()=>{mounted=false;subscription.unsubscribe()}},[]);
 const signIn=async(email:string,password:string)=>{signingInRef.current=true;try{const {data,error}=await withTimeout(supabase.auth.signInWithPassword({email,password}),SIGN_IN_TIMEOUT_MS);if(error)return{error:error.message};if(!data.session?.user)return{error:'تعذر إنشاء جلسة تسجيل الدخول.'};setSession(data.session);setUser(data.session.user);const nextProfile=await fetchProfile(data.session.user.id,data.session.user);if(!nextProfile)return{error:'تم تسجيل الدخول لكن تعذر تحميل ملف المستخدم. تحقق من صلاحيات الحساب ثم أعد المحاولة.'};setProfile(nextProfile);return{error:null}}catch(error){console.error('Sign-in failed:',error);return{error:'تعذر إكمال تسجيل الدخول. يرجى المحاولة مرة أخرى.'}}finally{signingInRef.current=false;setLoading(false)}};
 const requestPasswordReset=async(email:string)=>{try{const redirectTo='https://mizanafter.vercel.app/';const {error}=await withTimeout(supabase.auth.resetPasswordForEmail(email,{redirectTo}),PASSWORD_RESET_TIMEOUT_MS);return{error:error?.message??null}}catch(error){console.error('Password reset request failed:',error);return{error:'تعذر إرسال رابط استعادة كلمة المرور. يرجى المحاولة مرة أخرى.'}}};
 const updatePassword=async(password:string)=>{try{const {error}=await withTimeout(supabase.auth.updateUser({password}),PASSWORD_RESET_TIMEOUT_MS);return{error:error?.message??null}}catch(error){console.error('Password update failed:',error);return{error:'تعذر تحديث كلمة المرور. يرجى المحاولة مرة أخرى.'}}};
 const signOut=async()=>{await supabase.auth.signOut();setSession(null);setUser(null);setProfile(null);setLoading(false)};
 return <AuthContext.Provider value={{session,user,profile,loading,signIn,requestPasswordReset,updatePassword,signOut,refreshProfile}}>{children}</AuthContext.Provider>
}
export function useAuth(){const ctx=useContext(AuthContext);if(!ctx)throw new Error('useAuth must be used within AuthProvider');return ctx}